#!/usr/bin/env node

/**
 * Seed the Learn / Education section. Safe to re-run: each entry has a fixed id,
 * so it is replaced, not duplicated. Add or edit entries in Studio afterward.
 *
 * Usage:  node scripts/seed-guides.mjs
 */

import { createClient } from "@sanity/client";
import { readFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const envFile = readFileSync(resolve(__dirname, "../.env.local"), "utf-8");
const env = {};
for (const line of envFile.split("\n")) {
  const t = line.trim();
  if (!t || t.startsWith("#")) continue;
  const [k, ...rest] = t.split("=");
  env[k.trim()] = rest.join("=").trim();
}

const projectId = env.NEXT_PUBLIC_SANITY_PROJECT_ID;
const token = env.SANITY_API_TOKEN;
if (!projectId || !token) {
  console.error("Missing NEXT_PUBLIC_SANITY_PROJECT_ID or SANITY_API_TOKEN in .env.local");
  process.exit(1);
}
const client = createClient({
  projectId,
  dataset: env.NEXT_PUBLIC_SANITY_DATASET || "production",
  token,
  apiVersion: "2024-01-01",
  useCdn: false,
});

const g = (slug, title, category, order, summary, body) => ({
  _id: `guide-${slug}`,
  _type: "guide",
  title,
  slug: { _type: "slug", current: slug },
  category,
  order,
  summary,
  body,
});

const GUIDES = [
  // ── Web Design ──────────────────────────────────────────────
  g("responsive-design", "What is responsive design?", "Web Design", 1,
    "A site that adjusts its layout to look right on phones, tablets, and desktops.",
    ["Responsive design means the same website reshapes itself to fit whatever screen it is on, instead of forcing you to pinch and zoom on a phone.",
     "Most of your visitors are on mobile, so every site we build is mobile-first by default."]),
  g("ux-vs-ui", "What is the difference between UX and UI?", "Web Design", 2,
    "UX is how a site works and feels to use. UI is how it looks.",
    ["UI (user interface) is the visual layer: colors, buttons, fonts, spacing. UX (user experience) is the bigger picture of whether the site is easy and pleasant to use.",
     "A site can look beautiful and still have poor UX if people cannot find what they need."]),
  g("landing-page", "What is a landing page?", "Web Design", 3,
    "A single focused page built to get a visitor to take one action.",
    ["A landing page strips away distractions and points everything at one goal, like booking a call or capturing a lead.",
     "They are common for ads and campaigns because the focus tends to convert better than a general page."]),
  g("wireframe", "What is a wireframe?", "Web Design", 4,
    "A simple black-and-white sketch of a page's layout before design starts.",
    ["A wireframe shows where things go (header, sections, buttons) without colors or final content, so we agree on structure early.",
     "It is faster and cheaper to move boxes in a wireframe than to redo a finished design."]),
  g("cms", "What is a CMS?", "Web Design", 5,
    "A Content Management System lets you edit your site without touching code.",
    ["A CMS is the dashboard where you change text, images, prices, and posts yourself. We use Sanity, which is fast and clean.",
     "It means you are not paying a developer every time you want to fix a typo or add a blog post."]),
  g("favicon", "What is a favicon?", "Web Design", 6,
    "The tiny icon that shows in the browser tab next to your site's name.",
    ["A favicon is your logo shrunk down to a small square that appears in tabs, bookmarks, and history. It is a small but real branding detail.",
     "We set it up from your logo as part of every build."]),
  g("accessibility", "What is web accessibility?", "Web Design", 7,
    "Building a site so people with disabilities can use it too.",
    ["Accessibility (often shortened to a11y) covers things like keyboard navigation, screen-reader labels, and good color contrast.",
     "It is the right thing to do, it widens your audience, and it overlaps with good SEO."]),
  g("cta", "What is a call to action?", "Web Design", 8,
    "The button or link that tells visitors the next step to take.",
    ["A call to action (CTA) is a clear prompt like Book a Free Consultation or Get a Quote. Every page should have one obvious next step.",
     "Weak or missing CTAs are one of the most common reasons sites do not convert."]),
  g("static-vs-dynamic", "Static vs dynamic website: what is the difference?", "Web Design", 9,
    "Static sites serve fixed pages. Dynamic sites build pages on the fly from data.",
    ["A static site is fast and cheap and great for marketing pages. A dynamic site pulls from a database to show things like logins, bookings, or live inventory.",
     "Many modern sites, including this one, mix both for speed and flexibility."]),
  g("spa", "What is a single-page application?", "Web Design", 10,
    "A site that loads once and updates content without full page reloads.",
    ["A single-page application (SPA) feels app-like: clicking around updates the screen instantly instead of reloading the whole page.",
     "It is great for dashboards and tools, though plain pages are often better for marketing and SEO."]),

  // ── Domains & DNS ───────────────────────────────────────────
  g("domain", "What is a domain?", "Domains & DNS", 1,
    "Your website's address on the internet, like luwahtechnologies.com.",
    ["A domain is the name people type to reach your site. You rent it yearly from a registrar for about $12 to $15 a year.",
     "Owning a domain is separate from hosting. The domain is the address. Hosting is where the site lives."]),
  g("dns", "What is DNS?", "Domains & DNS", 2,
    "The internet's phone book. It points your domain to the server your site lives on.",
    ["DNS (Domain Name System) translates your domain name into the numeric address of the server hosting your site.",
     "When you change hosts, you update DNS records to point the domain at the new server. Changes can take minutes to hours."]),
  g("subdomain", "What is a subdomain?", "Domains & DNS", 3,
    "A prefix on your domain, like shop.yoursite.com or blog.yoursite.com.",
    ["A subdomain lets you run a separate section or app under your main domain without buying a new one.",
     "Common uses are a store, a help center, or a staging version of your site."]),
  g("domain-registrar", "What is a domain registrar?", "Domains & DNS", 4,
    "The company you buy and manage your domain name through.",
    ["A registrar (GoDaddy, Namecheap, Cloudflare) is where you register a domain and renew it each year.",
     "We help you pick one and point it at your site, and you keep full ownership of the name."]),

  // ── Hosting & Servers ───────────────────────────────────────
  g("web-hosting", "What is web hosting?", "Hosting & Servers", 1,
    "The service that keeps your website online and reachable 24/7.",
    ["Hosting is renting space on a server that is always on, so visitors can load your site any time.",
     "Static hosting is cheap and fits marketing sites. App hosting runs sites with databases and logins. We pick the right one for your build."]),
  g("shared-hosting", "What is shared hosting?", "Hosting & Servers", 2,
    "Many websites sharing one server to keep costs low.",
    ["Shared hosting puts your site on a server alongside many others, which makes it cheap but can slow down if a neighbor gets busy.",
     "It is fine for small sites, but a VPS or cloud hosting gives more consistent performance."]),
  g("vps", "What is a VPS?", "Hosting & Servers", 3,
    "A Virtual Private Server: your own slice of a server with full control.",
    ["A VPS gives you a dedicated portion of a physical server, with your own resources, for more control and steadier performance than shared hosting.",
     "Good for custom apps, heavier traffic, or when you need software a simple host will not allow."]),
  g("cloud-hosting", "What is cloud hosting?", "Hosting & Servers", 4,
    "Hosting spread across many servers that scales up and down with demand.",
    ["Cloud hosting runs your site across a pool of servers, so it can handle traffic spikes and you pay for what you use.",
     "Render, Vercel, and AWS are common examples. It is what most of the sites we build run on."]),
  g("cdn", "What is a CDN?", "Hosting & Servers", 5,
    "A Content Delivery Network serves your site from locations near each visitor for speed.",
    ["A CDN keeps copies of your site on servers around the world, so a visitor in Florida loads it from a nearby server instead of one far away.",
     "It makes pages faster and absorbs traffic spikes. Cloudflare is the common one, and it doubles as a security layer."]),
  g("uptime", "What is uptime?", "Hosting & Servers", 6,
    "The percentage of time your site is online and working.",
    ["Uptime measures reliability. 99.9% uptime means your site is down only a few minutes a month.",
     "We monitor uptime so problems are caught before your customers notice."]),
  g("bandwidth", "What is bandwidth?", "Hosting & Servers", 7,
    "How much data your site can send to visitors over time.",
    ["Bandwidth is like the width of a pipe: more bandwidth means more visitors and bigger files (images, video) without slowdowns.",
     "Most small business sites never come close to their limit, but media-heavy sites need more."]),
  g("database", "What is a database?", "Hosting & Servers", 8,
    "Organized storage for your site's data, like bookings, users, or products.",
    ["A database holds structured information your site reads and writes, such as customer records or inventory.",
     "Static marketing sites may not need one. Booking systems, logins, and stores do."]),
  g("api", "What is an API?", "Hosting & Servers", 9,
    "A way for two pieces of software to talk to each other.",
    ["An API (Application Programming Interface) lets your site connect to other tools, like a payment processor, a calendar, or an AI model.",
     "It is how automations stitch your apps together without manual copy-paste."]),

  // ── Hardware ────────────────────────────────────────────────
  g("server", "What is a server?", "Hardware", 1,
    "A computer that runs all the time to deliver websites, apps, or files to others.",
    ["A server is a computer built to stay on and respond to requests. When you visit a website, a server sends the pages to your browser.",
     "It can be a physical machine in a rack, a virtual slice of one (a VPS), or a managed cloud service."]),
  g("server-rack", "What is a server rack?", "Hardware", 2,
    "A standardized frame that holds servers, switches, and other gear in one place.",
    ["A server rack is a metal frame, measured in units called U, that stacks computing equipment vertically to save space.",
     "Data centers and server rooms use racks to house the machines that run websites and apps."]),
  g("cpu", "What is a CPU?", "Hardware", 3,
    "The processor: the part of a computer that does the actual thinking.",
    ["The CPU (central processing unit) carries out instructions and calculations. More and faster cores handle more work at once.",
     "For a server, a stronger CPU means it can serve more visitors or run heavier tasks."]),
  g("ram", "What is RAM?", "Hardware", 4,
    "Short-term memory a computer uses for whatever it is actively working on.",
    ["RAM (random access memory) holds the data a server is using right now. Run out of it and things slow down or crash.",
     "This site once hit a memory limit on a small plan, which is a good example of why RAM matters."]),
  g("storage-ssd-hdd", "SSD vs HDD: what is the difference?", "Hardware", 5,
    "Both store files. SSDs are much faster; HDDs are cheaper per gigabyte.",
    ["An SSD (solid state drive) has no moving parts and reads data quickly, which makes sites and apps feel snappy. An HDD (hard disk drive) spins a physical disk and is slower but cheaper for bulk storage.",
     "Modern servers and websites run on SSDs."]),

  // ── Networking ──────────────────────────────────────────────
  g("ip-address", "What is an IP address?", "Networking", 1,
    "The numeric address that identifies a device on a network.",
    ["An IP address is like a mailing address for a computer, phone, or server. Data finds its way to the right place using it.",
     "Public IPs are visible on the internet. Private IPs are used inside your home or office network."]),
  g("vlan", "What is a VLAN?", "Networking", 2,
    "A Virtual LAN splits one physical network into separate, isolated networks.",
    ["A VLAN lets you divide one network into groups that cannot see each other, even though they share the same hardware.",
     "It is used for security. Guest WiFi, office computers, and cameras can each sit on their own VLAN so a problem on one does not reach the others."]),
  g("firewall", "What is a firewall?", "Networking", 3,
    "A barrier that controls what traffic is allowed in and out of a network.",
    ["A firewall checks incoming and outgoing connections against rules and blocks anything not allowed.",
     "It is a first line of defense, and every site and server we run sits behind one."]),
  g("router", "What is a router?", "Networking", 4,
    "The device that directs traffic between your network and the internet.",
    ["A router connects your local network to the wider internet and decides where data should go next.",
     "It is the box your internet provider gives you, and in larger setups it is dedicated hardware."]),
  g("network-switch", "What is a network switch?", "Networking", 5,
    "A device that connects multiple machines on the same local network.",
    ["A switch lets computers, servers, and printers on one network talk to each other efficiently, sending data only to the device that needs it.",
     "In a server rack, a switch ties all the equipment together."]),
  g("vpn", "What is a VPN?", "Networking", 6,
    "A private, encrypted tunnel over the public internet.",
    ["A VPN (virtual private network) hides your traffic and can make you appear to connect from somewhere else, which helps privacy and secure remote access.",
     "Businesses use VPNs so staff can reach internal systems safely from anywhere."]),
  g("latency", "What is latency?", "Networking", 7,
    "The delay between a request and the response. Lower is better.",
    ["Latency, often called ping, is how long data takes to travel. High latency makes sites and calls feel laggy.",
     "Serving content from nearby (a CDN) is one way we keep latency low."]),
  g("port", "What is a port?", "Networking", 8,
    "A numbered channel on a device for a specific kind of traffic.",
    ["Ports let one machine handle many services at once. Websites use port 443 for secure traffic, for example.",
     "Firewalls open and close ports to control what is reachable."]),
  g("http-https", "HTTP vs HTTPS: what is the difference?", "Networking", 9,
    "HTTPS is HTTP with encryption. The S stands for secure.",
    ["HTTP moves web pages between server and browser. HTTPS does the same but encrypts it, so no one can read or tamper with the data in transit.",
     "Browsers warn visitors away from plain HTTP, so every site we build uses HTTPS."]),

  // ── Security ────────────────────────────────────────────────
  g("ssl", "What is SSL / HTTPS?", "Security", 1,
    "The padlock in the browser. It encrypts data between your site and visitors.",
    ["SSL (now technically TLS) encrypts the connection so passwords and form data cannot be read in transit. Secure sites show https and a padlock.",
     "Google ranks secure sites higher and browsers flag insecure ones. Every site we build includes it, set up free."]),
  g("two-factor", "What is two-factor authentication?", "Security", 2,
    "A second login step beyond your password, like a code from your phone.",
    ["Two-factor authentication (2FA) means even if someone steals your password, they still cannot log in without the second factor.",
     "Turn it on everywhere it is offered. It is one of the highest-value security habits."]),
  g("ddos", "What is a DDoS attack?", "Security", 3,
    "Flooding a site with fake traffic to knock it offline.",
    ["A DDoS (distributed denial of service) attack overwhelms a server with junk requests so real visitors cannot get through.",
     "A CDN and firewall like Cloudflare absorb most of these before they reach your site."]),
  g("encryption", "What is encryption?", "Security", 4,
    "Scrambling data so only the right person can read it.",
    ["Encryption turns readable information into a coded form that needs a key to unlock, protecting it in transit and at rest.",
     "It is what keeps passwords, payments, and private data safe."]),

  // ── AI ──────────────────────────────────────────────────────
  g("llm", "What is an LLM?", "AI", 1,
    "A Large Language Model is the AI that understands and writes text, like Claude.",
    ["An LLM is trained on huge amounts of text so it can answer questions, summarize, write, and reason in plain language.",
     "It is the engine behind chatbots, writing assistants, and most of the AI features we build."]),
  g("prompt", "What is a prompt?", "AI", 2,
    "The instruction or question you give an AI to get a result.",
    ["A prompt is what you type to an AI. The clearer and more specific it is, the better the output.",
     "Good prompts include the goal, any context, and the format you want back."]),
  g("prompt-engineering", "What is prompt engineering?", "AI", 3,
    "The skill of writing prompts that get reliable, high-quality AI output.",
    ["Prompt engineering is crafting and refining instructions so an AI does exactly what you need, consistently.",
     "It is the difference between a vague answer and a useful one, especially inside automations."]),
  g("ai-agent", "What is an AI agent?", "AI", 4,
    "An AI that can take actions and use tools, not just chat.",
    ["An AI agent goes beyond answering. It can plan steps and use tools, like searching, sending an email, or updating a record, to finish a task.",
     "Agents are what turn AI from a chatbot into something that actually does work for you."]),
  g("ai-skill", "What is an AI skill?", "AI", 5,
    "A packaged capability that teaches an AI agent how to do a specific job.",
    ["A skill bundles instructions, examples, and sometimes tools so an agent reliably handles a defined task, like reviewing code or drafting a proposal.",
     "Skills make an agent's behavior consistent and reusable across jobs."]),
  g("rag", "What is RAG?", "AI", 6,
    "Retrieval Augmented Generation: letting an AI look things up before it answers.",
    ["RAG gives an AI access to your documents or data so it answers from real, current sources instead of memory alone.",
     "It is how you build an assistant that knows your business's specifics and stays accurate."]),
  g("ai-token", "What is a token in AI?", "AI", 7,
    "A chunk of text an AI reads and writes. Pricing and limits are measured in tokens.",
    ["A token is roughly a few characters or part of a word. AI models break text into tokens to process it.",
     "Usage is billed per token, and each model has a limit on how many it can handle at once."]),
  g("hallucination", "What is an AI hallucination?", "AI", 8,
    "When an AI states something false but sounds confident.",
    ["A hallucination is a made-up fact, name, or number presented as if it were true. It happens because the model predicts plausible text.",
     "This is why a human should review AI output, and why grounding it in real data (RAG) helps."]),
  g("context-window", "What is a context window?", "AI", 9,
    "How much text an AI can consider at once.",
    ["The context window is the AI's working memory for a conversation, measured in tokens. Go past it and earlier details drop off.",
     "Bigger windows let the AI handle long documents and longer chats."]),
  g("mcp", "What is MCP?", "AI", 10,
    "Model Context Protocol: a standard way to connect AI to your tools and data.",
    ["MCP is a common plug for hooking an AI agent up to apps, files, and services so it can act on them safely.",
     "It is part of how we connect AI to the systems a business already uses."]),
  g("chatbot-vs-agent", "Chatbot vs AI agent: what is the difference?", "AI", 11,
    "A chatbot talks. An agent talks and takes action.",
    ["A chatbot answers questions in a conversation. An agent can also use tools to do things, like book an appointment or update a spreadsheet.",
     "For most businesses, the value is in agents that complete tasks, not just answer."]),

  // ── SEO & Marketing ─────────────────────────────────────────
  g("seo", "What is SEO?", "SEO & Marketing", 1,
    "Search Engine Optimization: getting found on Google without paying for ads.",
    ["SEO is the work that helps your site rank in Google for what your customers search.",
     "It means fast pages, clear titles, a sitemap, and useful content. It compounds over time, unlike ads that stop when you stop paying."]),
  g("backlink", "What is a backlink?", "SEO & Marketing", 2,
    "A link from another website to yours. Google treats it as a vote of trust.",
    ["Backlinks from reputable sites tell search engines your content is credible, which helps rankings.",
     "Quality matters more than quantity. A few trusted links beat many spammy ones."]),
  g("keywords", "What are keywords?", "SEO & Marketing", 3,
    "The words and phrases people type into search that you want to rank for.",
    ["Keywords are the search terms your customers use, like automate appointment reminders. Your content should match how they actually search.",
     "Long, specific phrases are easier to rank for than broad single words."]),
];

const tx = client.transaction();
for (const doc of GUIDES) tx.createOrReplace(doc);
await tx.commit();
console.log(`OK: seeded ${GUIDES.length} Learn entries into ${client.config().dataset}`);
